-- MySQL Script generated by MySQL Workbench
-- Mon Jun 13 20:11:29 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema voto_electronico
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema voto_electronico
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `voto_electronico` DEFAULT CHARACTER SET utf8mb4 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`tipo_votacionPaga`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tipo_votacionPaga` (
  `idtipo_votacion_paga` INT NOT NULL,
  `cantidad_limite` VARCHAR(45) NOT NULL,
  `usos_limite` VARCHAR(45) NULL,
  PRIMARY KEY (`idtipo_votacion_paga`))
ENGINE = InnoDB;

USE `voto_electronico` ;

-- -----------------------------------------------------
-- Table `voto_electronico`.`pais`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `voto_electronico`.`pais` (
  `idPais` INT NOT NULL AUTO_INCREMENT,
  `NombrePais` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idPais`),
  UNIQUE INDEX `Nombre_UNIQUE` (`NombrePais` ASC) VISIBLE,
  UNIQUE INDEX `idPais_UNIQUE` (`idPais` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `voto_electronico`.`provincia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `voto_electronico`.`provincia` (
  `idProvincia` INT NOT NULL AUTO_INCREMENT,
  `NombreProvincia` VARCHAR(45) NOT NULL,
  `idPais` INT NOT NULL,
  PRIMARY KEY (`idProvincia`),
  UNIQUE INDEX `idProvincia_UNIQUE` (`idProvincia` ASC) VISIBLE,
  INDEX `fk_pais_provincia` (`idPais` ASC) VISIBLE,
  CONSTRAINT `fk_pais_provincia`
    FOREIGN KEY (`idPais`)
    REFERENCES `voto_electronico`.`pais` (`idPais`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `voto_electronico`.`ciudad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `voto_electronico`.`ciudad` (
  `idCiudad` INT NOT NULL AUTO_INCREMENT,
  `NombreCiudad` VARCHAR(45) NOT NULL,
  `idProvincia` INT NOT NULL,
  PRIMARY KEY (`idCiudad`),
  UNIQUE INDEX `idCiudad_UNIQUE` (`idCiudad` ASC) VISIBLE,
  INDEX `fk_ciudad_provincia` (`idProvincia` ASC) VISIBLE,
  CONSTRAINT `fk_ciudad_provincia`
    FOREIGN KEY (`idProvincia`)
    REFERENCES `voto_electronico`.`provincia` (`idProvincia`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `voto_electronico`.`estado_votacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `voto_electronico`.`estado_votacion` (
  `idestado_Votacion` INT NOT NULL AUTO_INCREMENT,
  `descripcion_estado` BIT NOT NULL,
  PRIMARY KEY (`idestado_Votacion`),
  UNIQUE INDEX `idestado_Votacion_UNIQUE` (`idestado_Votacion` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `voto_electronico`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `voto_electronico`.`usuario` (
  `idusuario` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NOT NULL,
  `Apellido` VARCHAR(45) NOT NULL,
  `Telefono` VARCHAR(45) NOT NULL,
  `DNI` VARCHAR(45) NOT NULL,
  `usuario_bajaLogica` DATE NULL,
  PRIMARY KEY (`idusuario`),
  UNIQUE INDEX `idusuario_UNIQUE` (`idusuario` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `voto_electronico`.`login`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `voto_electronico`.`login` (
  `idLogin` INT NOT NULL AUTO_INCREMENT,
  `userName` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `login_bajaLogica` DATE NULL,
  `usuario_idusuario` INT NOT NULL,
  PRIMARY KEY (`idLogin`),
  UNIQUE INDEX `idLogin_UNIQUE` (`idLogin` ASC) VISIBLE,
  INDEX `fk_login_usuario1_idx` (`usuario_idusuario` ASC) VISIBLE,
  CONSTRAINT `fk_login_usuario1`
    FOREIGN KEY (`usuario_idusuario`)
    REFERENCES `voto_electronico`.`usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `voto_electronico`.`votacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `voto_electronico`.`votacion` (
  `idVotacion` INT NOT NULL AUTO_INCREMENT,
  `descripcion_Votacion` VARCHAR(45) NOT NULL,
  `fecha_inicio` DATE NOT NULL,
  `fecha_cierre` DATE NOT NULL,
  `para_Todos` VARCHAR(45) NOT NULL,
  `Resultado_idResultado` INT NOT NULL,
  `estado_Votacion_idestado_Votacion` INT NOT NULL,
  `tipo_votacion_paga_idtipo_votacion_paga` INT NOT NULL,
  `login_idLogin` INT NOT NULL,
  PRIMARY KEY (`idVotacion`),
  UNIQUE INDEX `idVotacion_UNIQUE` (`idVotacion` ASC) VISIBLE,
  INDEX `fk_Votacion_estado_Votacion1_idx` (`estado_Votacion_idestado_Votacion` ASC) VISIBLE,
  INDEX `fk_Votacion_Resultado1_idx` (`Resultado_idResultado` ASC) VISIBLE,
  INDEX `fk_votacion_tipo_votacion_paga1_idx` (`tipo_votacion_paga_idtipo_votacion_paga` ASC) VISIBLE,
  INDEX `fk_votacion_login1_idx` (`login_idLogin` ASC) VISIBLE,
  CONSTRAINT `fk_Votacion_estado_Votacion1`
    FOREIGN KEY (`estado_Votacion_idestado_Votacion`)
    REFERENCES `voto_electronico`.`estado_votacion` (`idestado_Votacion`),
  CONSTRAINT `fk_votacion_tipo_votacion_paga1`
    FOREIGN KEY (`tipo_votacion_paga_idtipo_votacion_paga`)
    REFERENCES `mydb`.`tipo_votacionPaga` (`idtipo_votacion_paga`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_votacion_login1`
    FOREIGN KEY (`login_idLogin`)
    REFERENCES `voto_electronico`.`login` (`idLogin`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `voto_electronico`.`opcion_votacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `voto_electronico`.`opcion_votacion` (
  `idopcion_Votacion` INT NOT NULL AUTO_INCREMENT,
  `Votacion_idVotacion` INT NOT NULL,
  `opcion_votacion` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(45) NULL,
  PRIMARY KEY (`idopcion_Votacion`),
  UNIQUE INDEX `idopcion_Votacion_UNIQUE` (`idopcion_Votacion` ASC) VISIBLE,
  INDEX `fk_opcion_Votacion_Votacion1_idx` (`Votacion_idVotacion` ASC) VISIBLE,
  CONSTRAINT `fk_opcion_Votacion_Votacion1`
    FOREIGN KEY (`Votacion_idVotacion`)
    REFERENCES `voto_electronico`.`votacion` (`idVotacion`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `voto_electronico`.`voto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `voto_electronico`.`voto` (
  `idDesc_Voto` INT NOT NULL AUTO_INCREMENT,
  `votoRealizado` BIT NOT NULL,
  `fecha_voto` DATE NOT NULL,
  `opcion_Votacion_idopcion_Votacion` INT NOT NULL,
  PRIMARY KEY (`idDesc_Voto`),
  UNIQUE INDEX `idDesc_Voto_UNIQUE` (`idDesc_Voto` ASC) VISIBLE,
  INDEX `fk_desc_Voto_opcion_Votacion1_idx` (`opcion_Votacion_idopcion_Votacion` ASC) VISIBLE,
  CONSTRAINT `fk_desc_Voto_opcion_Votacion1`
    FOREIGN KEY (`opcion_Votacion_idopcion_Votacion`)
    REFERENCES `voto_electronico`.`opcion_votacion` (`idopcion_Votacion`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `voto_electronico`.`votante`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `voto_electronico`.`votante` (
  `idgrupo_Votacion` INT NOT NULL AUTO_INCREMENT,
  `Votacion_idVotacion` INT NOT NULL,
  `email` VARCHAR(45) NULL,
  `telefono` VARCHAR(45) NULL,
  `voto_idDesc_Voto` INT NOT NULL,
  PRIMARY KEY (`idgrupo_Votacion`),
  UNIQUE INDEX `idgrupo_Votacion_UNIQUE` (`idgrupo_Votacion` ASC) VISIBLE,
  INDEX `fk_grupo_Votacion_Votacion1_idx` (`Votacion_idVotacion` ASC) VISIBLE,
  INDEX `fk_votante_voto1_idx` (`voto_idDesc_Voto` ASC) VISIBLE,
  CONSTRAINT `fk_grupo_Votacion_Votacion1`
    FOREIGN KEY (`Votacion_idVotacion`)
    REFERENCES `voto_electronico`.`votacion` (`idVotacion`),
  CONSTRAINT `fk_votante_voto1`
    FOREIGN KEY (`voto_idDesc_Voto`)
    REFERENCES `voto_electronico`.`voto` (`idDesc_Voto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `voto_electronico`.`resultado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `voto_electronico`.`resultado` (
  `idResultado` INT NOT NULL AUTO_INCREMENT,
  `descripcion_Resultado` VARCHAR(45) NOT NULL,
  `votacion_idVotacion` INT NOT NULL,
  PRIMARY KEY (`idResultado`),
  UNIQUE INDEX `idResultado_UNIQUE` (`idResultado` ASC) VISIBLE,
  INDEX `fk_resultado_votacion1_idx` (`votacion_idVotacion` ASC) VISIBLE,
  CONSTRAINT `fk_resultado_votacion1`
    FOREIGN KEY (`votacion_idVotacion`)
    REFERENCES `voto_electronico`.`votacion` (`idVotacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `voto_electronico`.`ubicacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `voto_electronico`.`ubicacion` (
  `idUbicacion` INT NOT NULL AUTO_INCREMENT,
  `idCiudad` INT NOT NULL,
  `idusuario` INT NOT NULL,
  PRIMARY KEY (`idUbicacion`),
  UNIQUE INDEX `idUbicacion_UNIQUE` (`idUbicacion` ASC) VISIBLE,
  INDEX `fk_ubicacion_usuario` (`idusuario` ASC) VISIBLE,
  INDEX `fk_Ubicacion_ciudad` (`idCiudad` ASC) VISIBLE,
  CONSTRAINT `fk_Ubicacion_ciudad`
    FOREIGN KEY (`idCiudad`)
    REFERENCES `voto_electronico`.`ciudad` (`idCiudad`),
  CONSTRAINT `fk_ubicacion_usuario`
    FOREIGN KEY (`idusuario`)
    REFERENCES `voto_electronico`.`usuario` (`idusuario`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
